### ISSUE TITLE
Jellyfish module

### ISSUE THREAD

**Issue by michaeloc** [MrPowers/ceja#4]
I'm try to use the library, but when I do toy example from the documentation an error appear:

ModuleNotFoundError: No module named 'jellyfish'

I'm try to install the module, but the problem continues.

**Comment by MrPowers** [comment]
I'm not sure I can help you given the information that's been provided.  I'm not sure where you've tried to install, what commands you've run, you virtual environment setup.  Don't know if this is a Databricks / EMR / or local issue.  Sorry I can't be of more help.
